/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xgl_demo_JniDemo */

#ifndef _Included_cn_xgl_demo_JniDemo
#define _Included_cn_xgl_demo_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xgl_demo_JniDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_xgl_demo_JniDemo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
