/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xgl_demo_JniHash */

#ifndef _Included_cn_xgl_demo_JniHash
#define _Included_cn_xgl_demo_JniHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xgl_demo_JniHash
 * Method:    hashString
 * Signature: (Ljava/lang/String;)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_cn_xgl_demo_JniHash_hashString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
